language: java
jdk:
- oraclejdk8
notifications:
  email:
  - ozwolf@gmail.com
env:
  global:
  - GPG_DIR="`pwd`/gpg"
  - secure: AIsFktK8dQVnEe1uF6Xjha8esxHrRvH0OnUgfuOw2C6iGet6fY9V8VsUbCnP6Qo5gRJC90cuOeuohJHLMKG8Pw79fdl0A2AvKVMMDd5Nb8TbXBAY/TBf7cuqSfwu2edy//XjxZejV3fMV1soL+0RR5ip3wCGyBRDDRtYwnu1RC4=
  - secure: D9GGrQ+fs1CdenLuc47G2aowU53RM7pJQifZG/X12olZI3lZZEWdcsZNvFrBNIg/VRZVe27AO68tWN//sy7K+wkAsPDZDZjI2Rv4YVQ0HZu+imFkLn+FvltKM3luywVtDaPUxINKsi/AfRWzOS7LRwVU2qYDR7qSs+g0Wuvh0ns=
  - secure: QdARHzv+Qy8UALqg2/7nl0doLAgqrqSGHeW20aHDJgUflHlbYBPOwyG0844c7gpjSu8iN16+D0Xpzzj7ADi6qRnEM1MhPmQ+O7ZLVKPQPTvFUJDAjTSUrhPh43XenTlMYNus7BQERXBKX+iFrAFChb/UhuxKGh24+6oFlsA9ZUw=
  - secure: KHTH73gHzKmGFp/JJDrdcZwk6VI08K/8lnZl+0h0L226sEramZ8JSShNli6qmTs7V8IaxYdmoLbJPueImr8VsDVi1JmA14P3FnoFqlXZHqRfMk39rG6CyqucTG8Kow/2B3gyEdajUD0fzTHpFfSLv4Cq2SQmDJYuCrYbEytv6Ms=
  - secure: Bk9le3fp+36GUV3VvdX2RfZTDHwJo13ZlIZqoXKgyFUod3SMHgRynh72R9oYbW7yFkDrtTrS+NTdpWz7Xjt7VlkPpFs7OJ5CZ3YsTTu/ZGWvQ/N/T98H1w6/rZ9QRkuajdhMo3+cScHu+TaaXYRyauIH7KJLttsSQZb32p2mgP4=

before_script:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d

script:
- mvn -P ossrh clean source:jar deploy --settings travis-settings.xml
